### PR TITLE
After 1 step comes 2

### PR DESCRIPTION
**Pull request by alexdowad**
The main battle has been fought and won.

While the code cannot yet be legitimately described as "sweeter than candy", the parser generator is getting very, very readable. I already sense a tinge of sweetness there.

The major rough spot still left is the dark and twisted parser runtime. I could definitely clean it up, but strong test support would be needed, and we don't have that. In the meantime, I have read and understood enough of the runtime to have confidence that I can fix any bugs which are reported against it.

Regarding the runtime, I have a different idea. I'd like to see how much performance can be gained from making Racc generate, not parser tables, but Ruby/C code which embodies the states in the parser tables; I call this "making the instruction pointer your state variable", if you get what that means. I'm not ready to embark on that project quite yet, though.

### CODE REVIEW

**Comment by alexdowad** [comment]
Uh oh, looks like I broke Racc on 1.9.3 by using the newer `%i[]` syntax. Will fix.

**Comment by alexdowad** [comment]
A question on the changelog. f242c5c removes it, since the contents are long out of date.

Does anyone object to this? Should it be brought up to date, rather than deleted?

**Comment by alexdowad** [comment]
Personally, changelogs don't do much for me. I never read them. I just look at the git commit history if I want to know what has happened. But maybe other people are different.

**Comment by tenderlove** [comment]
Tbh, I don't either. I'm fine with it. If there is demand for adding a
change log, then let's do that later. I'd rather focus on improving the
software than doing book keeping.

**Comment by alexdowad** [comment]
OK, we are forging ahead here.

**Pull request merged**
