### PR TITLE
Remove forgotten debug printouts

### PR DESCRIPTION
**Pull request by pitr-ch**

### CODE REVIEW

**Comment by zenspider** [comment]
This isn't on master... but seems fine to me.

**Comment by pitr-ch** [comment]
yes, but the current line 1.4.x has it, and I am getting the output. Could you release a new version with the fix?

**Comment by alexdowad** [comment]
Looks good. Test suite passes when run locally; I don't know what happened on Travis CI (and don't really care). Merged.

Now if you want a new gem release... you will have to beg @tenderlove.

**Comment by pitr-ch** [comment]
@alexdowad Thank you! 
@tenderlove .send :bug:.gsub('u','e')

**Pull request closed without merging**
